package rise.naturalstyle;

import com.google.common.collect.Lists;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import rise.naturalstyle.common.NaturalConfig;
import rise.naturalstyle.init.BlockRegistry;
import rise.naturalstyle.init.ItemRegistry;
import rise.naturalstyle.proxy.CommonProxy;
import rise.naturalstyle.util.LogHelper;

@Mod(modid = NaturalStyle.MOD_ID, name = NaturalStyle.MOD_NAME, version = NaturalStyle.MOD_VERSION, useMetadata = true)
public class NaturalStyle {

    public static final String MOD_ID = "naturalstyle2";
    public static final String MOD_NAME = "NaturalStyle2";
    static final String MOD_VERSION = "1.12.2-r1";

    @SidedProxy(clientSide = "rise.naturalstyle.proxy.ClientProxy", serverSide = "rise.naturalstyle.proxy.CommonProxy")
    public static CommonProxy proxy;

    @Mod.Metadata
    private static ModMetadata meta;

    public static CreativeTabs TAB_NS = new CreativeTabs("naturalstyle")
    {
        @Override
        public ItemStack getTabIconItem()
        {
            return new ItemStack(Items.DIAMOND);
        }
    };

    @Mod.EventHandler
    public void PreInit(FMLPreInitializationEvent event)
    {
        new NaturalConfig().load(new Configuration(event.getSuggestedConfigurationFile()));

        LogHelper.load();
        this.info(meta);
        BlockRegistry.load();
        ItemRegistry.load();
    }

    @Mod.EventHandler
    public void Init(FMLInitializationEvent event)
    {
//        Recipes.load();
    }

    private void info(ModMetadata meta)
    {
        meta.modId = MOD_ID;
        meta.name = MOD_NAME;
        meta.version = MOD_VERSION;
        meta.authorList = Lists.newArrayList("RiSE4", "Hiroya-W");
        meta.description = "Excellent!";
        meta.autogenerated = false;
    }
}
